### PR TITLE
Add guides section

### PR DESCRIPTION
**Pull request by 2dpetkov**
The dYdX Ops subDAO suggest that the dYdX Chain Software documentation starts hosting some of the guides are currently available at docs.dydx.trade (the subDAO's fork of this repository):
- How to send USDC to dYdX
- How to set up Full Node
- How to uncross the Orderbook

### CODE REVIEW

**Comment by jiajames** [comment]
Could you help to clarify the difference of instructions for the "DYDX token holder" deployment and testnet deployment? Thanks

**Comment by 2dpetkov** [comment]
Thanks, @jiajames !
Here's what I think I can do for each guide, to make the guides align with your common

### How to send USDC from Ethereum to dYdX Chain
1. reword the title to not be about USDC and any chain in particular, but rather be about sending over the collateral token
2. add a "deployments" section in the beginning of the page, that points to the collateral token contracts for the different deployments
3. make sure it's explicitly stated that the screenshots and example commands are for the dYdX Token Holders' deployment

### How to set up a full node
1. add a "deployments" section in the beginning of the page, that shows Chain ID, example home folder, example moniker, link to resources for seeds and RPC endpoints to download genesis.json from, - for the different deployments
2. make sure it's explicitly stated that the screenshots and example commands are for the dYdX Token Holders' deployment

### How to uncross the orderbook
I think this one is ready as is - it is already referring to Testnet

**Comment by jiajames** [comment]
> 1. reword the title to not be about USDC and any chain in particular, but rather be about sending over the collateral token
sounds good, maybe "collateral/native" token is better

otherwise, sounds good! maybe one helpful thing would be to update the screenshot names also to indexer it is only for token holder deployment

**Comment by 2dpetkov** [comment]
Hey, @jiajames 
Thanks for the suggestions!

## How to send USDC from Ethereum to dYdX
Since the guide is not for depositing native token, and USDC is available on Sepolia, I've added the related Sepolia contract address in the **Deployments** section and only removed "chain" from the guide title: [commit](https://github.com/dydxprotocol/v4-documentation/pull/138/commits/ac26920a180d3e2058146dd5ec94a5c6c5a57874)

## How to set up a full node

Adding a **Deployments** would be very confusing, since it would contain links to the same pages - Network Constants and Resources. So instead, I added disclaimer note at the beginning of each step: [commit](https://github.com/dydxprotocol/v4-documentation/pull/138/commits/2dfa4ff3a2ffb4f93889bb560bcaaacd2e769384)

Comments on this new approach are welcome!

**Review by jiajames — APPROVED** [review]

**Pull request merged**
